{
 "title": "Cyber Power",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Power Source",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cyber_power_exporter_power_supplied_by",
     "legendFormat": "Power Source"
    }
   ]
  },
  {
   "title": "Battery State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cyber_power_exporter_state", "legendFormat": "Battery State" }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cyber_power_exporter_remaining_runtime",
     "legendFormat": "Runtime Remaining"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cyber_power_exporter_battery_capacity",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cyber_power_exporter_load_pct", "legendFormat": "Load Pct" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "cyber_power_exporter_utility_voltage",
     "legendFormat": "Utility Voltage"
    },
    {
     "expr": "cyber_power_exporter_output_voltage",
     "legendFormat": "Output Voltage"
    }
   ]
  },
  {
   "title": "Load Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "cyber_power_exporter_load_watts",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}